"""agents, tools, memory relations, device credentials

Revision ID: 1546f40d14ff
Revises: 736c4ff2bcca
Create Date: 2026-09-01 23:24:32.749727
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import thursday_shared.db.base

revision: str = "1546f40d14ff"
down_revision: str | None = "736c4ff2bcca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("user_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("agent_type", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("capabilities", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("allowed_tools", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("permission_ceiling", sa.Integer(), nullable=False),
        sa.Column("configuration", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_agent_name_per_user"),
    )
    with op.batch_alter_table("agents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agents_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_agents_enabled"), ["enabled"], unique=False)
        batch_op.create_index(batch_op.f("ix_agents_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_agents_user_id"), ["user_id"], unique=False)

    op.create_table(
        "tools",
        sa.Column("user_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("capabilities", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("permission_level", sa.Integer(), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column("approval_policy", sa.String(length=16), nullable=False),
        sa.Column("supports_dry_run", sa.Boolean(), nullable=False),
        sa.Column("supports_undo", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_tool_name_per_user"),
    )
    with op.batch_alter_table("tools", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tools_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_tools_enabled"), ["enabled"], unique=False)
        batch_op.create_index(batch_op.f("ix_tools_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_tools_user_id"), ["user_id"], unique=False)

    op.create_table(
        "device_credentials",
        sa.Column("device_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("algorithm", sa.String(length=32), nullable=False),
        sa.Column("paired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rotates_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("device_credentials", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_device_credentials_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_device_credentials_device_id"), ["device_id"], unique=False
        )

    op.create_table(
        "memory_relations",
        sa.Column("from_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("to_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("relation", sa.String(length=24), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_id"],
            ["memories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_id"],
            ["memories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("memory_relations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_memory_relations_detected_at"), ["detected_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_memory_relations_from_id"), ["from_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_memory_relations_relation"), ["relation"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_memory_relations_to_id"), ["to_id"], unique=False)

    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.add_column(sa.Column("policy", sa.String(length=16), nullable=False))

    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("autonomy_level", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_column("autonomy_level")

    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.drop_column("policy")

    with op.batch_alter_table("memory_relations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memory_relations_to_id"))
        batch_op.drop_index(batch_op.f("ix_memory_relations_relation"))
        batch_op.drop_index(batch_op.f("ix_memory_relations_from_id"))
        batch_op.drop_index(batch_op.f("ix_memory_relations_detected_at"))

    op.drop_table("memory_relations")
    with op.batch_alter_table("device_credentials", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_device_credentials_device_id"))
        batch_op.drop_index(batch_op.f("ix_device_credentials_created_at"))

    op.drop_table("device_credentials")
    with op.batch_alter_table("tools", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tools_user_id"))
        batch_op.drop_index(batch_op.f("ix_tools_name"))
        batch_op.drop_index(batch_op.f("ix_tools_enabled"))
        batch_op.drop_index(batch_op.f("ix_tools_created_at"))

    op.drop_table("tools")
    with op.batch_alter_table("agents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agents_user_id"))
        batch_op.drop_index(batch_op.f("ix_agents_name"))
        batch_op.drop_index(batch_op.f("ix_agents_enabled"))
        batch_op.drop_index(batch_op.f("ix_agents_created_at"))

    op.drop_table("agents")
    # ### end Alembic commands ###
