"""model spend ledger

Revision ID: 234cb09e017d
Revises: f7c584518f25
Create Date: 2026-09-03 04:10:55.020262
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import thursday_shared.db.base

revision: str = "234cb09e017d"
down_revision: str | None = "f7c584518f25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_spend",
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("tier", sa.String(length=32), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("usd", sa.Float(), nullable=False),
        sa.Column("task_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("agent", sa.String(length=64), nullable=False),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("model_spend", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_model_spend_at"), ["at"], unique=False)
        batch_op.create_index(batch_op.f("ix_model_spend_provider"), ["provider"], unique=False)
        batch_op.create_index(batch_op.f("ix_model_spend_task_id"), ["task_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_model_spend_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model_spend", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_model_spend_user_id"))
        batch_op.drop_index(batch_op.f("ix_model_spend_task_id"))
        batch_op.drop_index(batch_op.f("ix_model_spend_provider"))
        batch_op.drop_index(batch_op.f("ix_model_spend_at"))

    op.drop_table("model_spend")
    # ### end Alembic commands ###
