"""task plan and verification nullable

Revision ID: 26294a50a735
Revises: 234cb09e017d
Create Date: 2026-09-03 04:30:31.410542
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import thursday_shared.db.base

revision: str = "26294a50a735"
down_revision: str | None = "234cb09e017d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.alter_column("plan", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("verification", existing_type=sa.TEXT(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.alter_column("verification", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column("plan", existing_type=sa.TEXT(), nullable=False)

    # ### end Alembic commands ###
