"""memory session id

Revision ID: 4f8c9e549d09
Revises: 1546f40d14ff
Create Date: 2026-09-02 05:05:02.477611
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import thursday_shared.db.base

revision: str = "4f8c9e549d09"
down_revision: str | None = "1546f40d14ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("memories", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("session_id", thursday_shared.db.base.GUID(length=36), nullable=True)
        )
        batch_op.create_index(batch_op.f("ix_memories_session_id"), ["session_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("memories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memories_session_id"))
        batch_op.drop_column("session_id")

    # ### end Alembic commands ###
