"""initial schema

Revision ID: 736c4ff2bcca
Revises:
Create Date: 2026-09-01 14:32:40.366449
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import thursday_shared.db.base

revision: str = "736c4ff2bcca"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("actor", sa.String(length=16), nullable=False),
        sa.Column("agent", sa.String(length=64), nullable=True),
        sa.Column("task_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("device_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("tool", sa.String(length=64), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource", sa.Text(), nullable=False),
        sa.Column("input_summary", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("output_summary", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("result", sa.String(length=16), nullable=False),
        sa.Column("permission_decision", sa.String(length=16), nullable=True),
        sa.Column("approval_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_hash"), ["hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_task_id"), ["task_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_tool"), ["tool"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_trace_id"), ["trace_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_ts"), ["ts"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("locale", sa.String(length=16), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("proactivity_level", sa.Integer(), nullable=False),
        sa.Column("voice_profile", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("settings", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_created_at"), ["created_at"], unique=False)

    op.create_table(
        "automations",
        sa.Column("user_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("trigger", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("conditions", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("actions", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("proactivity_min", sa.Integer(), nullable=False),
        sa.Column("budget", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("run_count", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=24), nullable=False),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("automations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_automations_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_automations_enabled"), ["enabled"], unique=False)
        batch_op.create_index(batch_op.f("ix_automations_user_id"), ["user_id"], unique=False)

    op.create_table(
        "devices",
        sa.Column("user_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("os", sa.String(length=64), nullable=False),
        sa.Column("os_version", sa.String(length=64), nullable=False),
        sa.Column("node_version", sa.String(length=32), nullable=False),
        sa.Column("fingerprint", sa.String(length=128), nullable=True),
        sa.Column("public_key", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("capabilities", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("telemetry", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("location_context", sa.String(length=64), nullable=True),
        sa.Column("trust_level", sa.Integer(), nullable=False),
        sa.Column("enrolled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_device_name_per_user"),
    )
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_devices_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_devices_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_devices_user_id"), ["user_id"], unique=False)

    op.create_table(
        "entities",
        sa.Column("user_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("aliases", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("attributes", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("embedding", thursday_shared.db.base.Vector(), nullable=True),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("entities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_entities_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_entities_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_entities_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_entities_user_id"), ["user_id"], unique=False)

    op.create_table(
        "goals",
        sa.Column("user_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("horizon", sa.String(length=24), nullable=False),
        sa.Column("parent_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["goals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("goals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_goals_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_goals_user_id"), ["user_id"], unique=False)

    op.create_table(
        "skills",
        sa.Column("user_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("owner", sa.String(length=64), nullable=False),
        sa.Column("risk", sa.String(length=16), nullable=False),
        sa.Column("tags", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "slug", name="uq_skill_slug_per_user"),
    )
    with op.batch_alter_table("skills", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_skills_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_skills_slug"), ["slug"], unique=False)
        batch_op.create_index(batch_op.f("ix_skills_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_skills_user_id"), ["user_id"], unique=False)

    op.create_table(
        "world_state",
        sa.Column("user_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("owner_status", sa.String(length=16), nullable=False),
        sa.Column("active_device_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("active_app", sa.String(length=120), nullable=True),
        sa.Column("active_project_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("active_task_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("online_devices", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("running_agents", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("pending_approvals", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("location_context", sa.String(length=64), nullable=True),
        sa.Column("open_files", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("recent_actions", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    with op.batch_alter_table("world_state", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_world_state_created_at"), ["created_at"], unique=False)

    op.create_table(
        "observations",
        sa.Column("user_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("device_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("object_label", sa.String(length=120), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("bbox", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("location_context", sa.String(length=64), nullable=True),
        sa.Column("frame_ref", sa.String(length=200), nullable=True),
        sa.Column("seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("observations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_observations_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_observations_object_label"), ["object_label"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_observations_seen_at"), ["seen_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_observations_user_id"), ["user_id"], unique=False)

    op.create_table(
        "permission_grants",
        sa.Column("user_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_glob", sa.String(length=500), nullable=False),
        sa.Column("device_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uses_remaining", sa.Integer(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("permission_grants", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_permission_grants_action"), ["action"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_permission_grants_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_permission_grants_user_id"), ["user_id"], unique=False)

    op.create_table(
        "projects",
        sa.Column("user_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("goal_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("vault_path", sa.String(length=500), nullable=True),
        sa.Column("blocked_on", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("metadata", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["goals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_projects_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_projects_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_projects_user_id"), ["user_id"], unique=False)

    op.create_table(
        "relationships",
        sa.Column("user_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("src_entity_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("dst_entity_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("kind", sa.String(length=48), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("attributes", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dst_entity_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["src_entity_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("relationships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_relationships_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_relationships_dst_entity_id"), ["dst_entity_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_relationships_kind"), ["kind"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_relationships_src_entity_id"), ["src_entity_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_relationships_user_id"), ["user_id"], unique=False)

    op.create_table(
        "skill_versions",
        sa.Column("skill_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("steps", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("tools", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("permissions", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("input_schema", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("output_schema", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("tests", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("changelog", sa.Text(), nullable=False),
        sa.Column("approved_by", sa.String(length=120), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("skill_id", "version", name="uq_skill_version"),
    )
    with op.batch_alter_table("skill_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_skill_versions_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_skill_versions_skill_id"), ["skill_id"], unique=False)

    op.create_table(
        "decisions",
        sa.Column("user_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("project_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("decision", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("alternatives", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.Column("impact", sa.Text(), nullable=False),
        sa.Column("vault_path", sa.Text(), nullable=True),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("decisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_decisions_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_decisions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "documents",
        sa.Column("user_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("project_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("vault_rel_path", sa.Text(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=True),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("mtime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tags", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("embedding", thursday_shared.db.base.Vector(), nullable=True),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_documents_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_documents_path"), ["path"], unique=False)
        batch_op.create_index(batch_op.f("ix_documents_user_id"), ["user_id"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("user_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("project_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("parent_task_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("goal_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("session_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("plan", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("assigned_agent", sa.String(length=64), nullable=True),
        sa.Column("origin_device_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("target_device_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("budget", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("spent", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("verification", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["goals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["origin_device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tasks_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_trace_id"), ["trace_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_tasks_user_status", ["user_id", "status"], unique=False)

    op.create_table(
        "approvals",
        sa.Column("user_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("task_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("step_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("agent", sa.String(length=64), nullable=True),
        sa.Column("device_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("resource", sa.Text(), nullable=False),
        sa.Column("risk", sa.String(length=16), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("expected_outcome", sa.Text(), nullable=False),
        sa.Column("consequence_of_refusal", sa.Text(), nullable=False),
        sa.Column("reversible", sa.Boolean(), nullable=False),
        sa.Column("dry_run", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_approvals_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_approvals_state"), ["state"], unique=False)
        batch_op.create_index(batch_op.f("ix_approvals_user_id"), ["user_id"], unique=False)

    op.create_table(
        "events",
        sa.Column("user_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("device_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("task_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("payload", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_occurred_at"), ["occurred_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_trace_id"), ["trace_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_user_id"), ["user_id"], unique=False)

    op.create_table(
        "memories",
        sa.Column("user_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("layer", sa.String(length=24), nullable=False),
        sa.Column("project_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("task_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("key", sa.String(length=200), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("structured", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("source_ref", sa.Text(), nullable=True),
        sa.Column("sensitivity", sa.Integer(), nullable=False),
        sa.Column("embedding", thursday_shared.db.base.Vector(), nullable=True),
        sa.Column("supersedes_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("superseded_by_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("access_count", sa.Integer(), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("memories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_memories_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_memories_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_memories_key"), ["key"], unique=False)
        batch_op.create_index(batch_op.f("ix_memories_layer"), ["layer"], unique=False)
        batch_op.create_index(batch_op.f("ix_memories_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_memories_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_memories_user_layer", ["user_id", "layer"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("user_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("device_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("task_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("suppressed_reason", sa.String(length=64), nullable=True),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notifications_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notifications_priority"), ["priority"], unique=False)
        batch_op.create_index(batch_op.f("ix_notifications_user_id"), ["user_id"], unique=False)

    op.create_table(
        "skill_runs",
        sa.Column("skill_version_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("task_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("sandbox", sa.Boolean(), nullable=False),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("output", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_version_id"],
            ["skill_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("skill_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_skill_runs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_skill_runs_skill_version_id"), ["skill_version_id"], unique=False
        )

    op.create_table(
        "task_steps",
        sa.Column("task_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("contract", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("depends_on", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("input", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("output", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("task_steps", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_task_steps_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_task_steps_task_id"), ["task_id"], unique=False)

    op.create_table(
        "agent_runs",
        sa.Column("task_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("step_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("agent_name", sa.String(length=64), nullable=False),
        sa.Column("agent_version", sa.String(length=32), nullable=False),
        sa.Column("contract", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("input_summary", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("output", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("verdict", sa.String(length=16), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["task_steps.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_runs_agent_name"), ["agent_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_runs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_runs_task_id"), ["task_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_runs_trace_id"), ["trace_id"], unique=False)

    op.create_table(
        "memory_conflicts",
        sa.Column("memory_id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("key", sa.String(length=200), nullable=True),
        sa.Column("old_value", sa.Text(), nullable=False),
        sa.Column("new_value", sa.Text(), nullable=False),
        sa.Column("old_source", sa.String(length=24), nullable=False),
        sa.Column("new_source", sa.String(length=24), nullable=False),
        sa.Column("old_confidence", sa.Float(), nullable=False),
        sa.Column("new_confidence", sa.Float(), nullable=False),
        sa.Column("old_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("new_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution", sa.String(length=24), nullable=False),
        sa.Column("resolved_by", sa.String(length=24), nullable=True),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["memory_id"],
            ["memories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("memory_conflicts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_memory_conflicts_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_memory_conflicts_memory_id"), ["memory_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_memory_conflicts_resolution"), ["resolution"], unique=False
        )

    op.create_table(
        "tool_runs",
        sa.Column("task_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("step_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("tool_name", sa.String(length=64), nullable=False),
        sa.Column("device_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("args_summary", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("result_summary", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("risk", sa.String(length=16), nullable=False),
        sa.Column("permission_decision", sa.String(length=16), nullable=True),
        sa.Column("approval_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("undo", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["task_steps.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tool_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tool_runs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_tool_runs_task_id"), ["task_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tool_runs_tool_name"), ["tool_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_tool_runs_trace_id"), ["trace_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tool_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tool_runs_trace_id"))
        batch_op.drop_index(batch_op.f("ix_tool_runs_tool_name"))
        batch_op.drop_index(batch_op.f("ix_tool_runs_task_id"))
        batch_op.drop_index(batch_op.f("ix_tool_runs_created_at"))

    op.drop_table("tool_runs")
    with op.batch_alter_table("memory_conflicts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memory_conflicts_resolution"))
        batch_op.drop_index(batch_op.f("ix_memory_conflicts_memory_id"))
        batch_op.drop_index(batch_op.f("ix_memory_conflicts_created_at"))

    op.drop_table("memory_conflicts")
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_runs_trace_id"))
        batch_op.drop_index(batch_op.f("ix_agent_runs_task_id"))
        batch_op.drop_index(batch_op.f("ix_agent_runs_created_at"))
        batch_op.drop_index(batch_op.f("ix_agent_runs_agent_name"))

    op.drop_table("agent_runs")
    with op.batch_alter_table("task_steps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_steps_task_id"))
        batch_op.drop_index(batch_op.f("ix_task_steps_created_at"))

    op.drop_table("task_steps")
    with op.batch_alter_table("skill_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skill_runs_skill_version_id"))
        batch_op.drop_index(batch_op.f("ix_skill_runs_created_at"))

    op.drop_table("skill_runs")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_user_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_priority"))
        batch_op.drop_index(batch_op.f("ix_notifications_created_at"))

    op.drop_table("notifications")
    with op.batch_alter_table("memories", schema=None) as batch_op:
        batch_op.drop_index("ix_memories_user_layer")
        batch_op.drop_index(batch_op.f("ix_memories_user_id"))
        batch_op.drop_index(batch_op.f("ix_memories_project_id"))
        batch_op.drop_index(batch_op.f("ix_memories_layer"))
        batch_op.drop_index(batch_op.f("ix_memories_key"))
        batch_op.drop_index(batch_op.f("ix_memories_expires_at"))
        batch_op.drop_index(batch_op.f("ix_memories_created_at"))

    op.drop_table("memories")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_user_id"))
        batch_op.drop_index(batch_op.f("ix_events_trace_id"))
        batch_op.drop_index(batch_op.f("ix_events_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_events_kind"))

    op.drop_table("events")
    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approvals_user_id"))
        batch_op.drop_index(batch_op.f("ix_approvals_state"))
        batch_op.drop_index(batch_op.f("ix_approvals_created_at"))

    op.drop_table("approvals")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index("ix_tasks_user_status")
        batch_op.drop_index(batch_op.f("ix_tasks_user_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_trace_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_status"))
        batch_op.drop_index(batch_op.f("ix_tasks_session_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_project_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_created_at"))

    op.drop_table("tasks")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_user_id"))
        batch_op.drop_index(batch_op.f("ix_documents_path"))
        batch_op.drop_index(batch_op.f("ix_documents_created_at"))

    op.drop_table("documents")
    with op.batch_alter_table("decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_decisions_user_id"))
        batch_op.drop_index(batch_op.f("ix_decisions_created_at"))

    op.drop_table("decisions")
    with op.batch_alter_table("skill_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skill_versions_skill_id"))
        batch_op.drop_index(batch_op.f("ix_skill_versions_created_at"))

    op.drop_table("skill_versions")
    with op.batch_alter_table("relationships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_relationships_user_id"))
        batch_op.drop_index(batch_op.f("ix_relationships_src_entity_id"))
        batch_op.drop_index(batch_op.f("ix_relationships_kind"))
        batch_op.drop_index(batch_op.f("ix_relationships_dst_entity_id"))
        batch_op.drop_index(batch_op.f("ix_relationships_created_at"))

    op.drop_table("relationships")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projects_user_id"))
        batch_op.drop_index(batch_op.f("ix_projects_status"))
        batch_op.drop_index(batch_op.f("ix_projects_created_at"))

    op.drop_table("projects")
    with op.batch_alter_table("permission_grants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_permission_grants_user_id"))
        batch_op.drop_index(batch_op.f("ix_permission_grants_created_at"))
        batch_op.drop_index(batch_op.f("ix_permission_grants_action"))

    op.drop_table("permission_grants")
    with op.batch_alter_table("observations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_observations_user_id"))
        batch_op.drop_index(batch_op.f("ix_observations_seen_at"))
        batch_op.drop_index(batch_op.f("ix_observations_object_label"))
        batch_op.drop_index(batch_op.f("ix_observations_expires_at"))

    op.drop_table("observations")
    with op.batch_alter_table("world_state", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_world_state_created_at"))

    op.drop_table("world_state")
    with op.batch_alter_table("skills", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skills_user_id"))
        batch_op.drop_index(batch_op.f("ix_skills_status"))
        batch_op.drop_index(batch_op.f("ix_skills_slug"))
        batch_op.drop_index(batch_op.f("ix_skills_created_at"))

    op.drop_table("skills")
    with op.batch_alter_table("goals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_goals_user_id"))
        batch_op.drop_index(batch_op.f("ix_goals_created_at"))

    op.drop_table("goals")
    with op.batch_alter_table("entities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_entities_user_id"))
        batch_op.drop_index(batch_op.f("ix_entities_name"))
        batch_op.drop_index(batch_op.f("ix_entities_kind"))
        batch_op.drop_index(batch_op.f("ix_entities_created_at"))

    op.drop_table("entities")
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_devices_user_id"))
        batch_op.drop_index(batch_op.f("ix_devices_status"))
        batch_op.drop_index(batch_op.f("ix_devices_created_at"))

    op.drop_table("devices")
    with op.batch_alter_table("automations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_automations_user_id"))
        batch_op.drop_index(batch_op.f("ix_automations_enabled"))
        batch_op.drop_index(batch_op.f("ix_automations_created_at"))

    op.drop_table("automations")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_created_at"))

    op.drop_table("users")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_user_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_ts"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_trace_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_tool"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_task_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_hash"))

    op.drop_table("audit_logs")
    # ### end Alembic commands ###
