"""model registry: endpoints, models, model_runs

Revision ID: 9d8757dd4d47
Revises: 26294a50a735
Create Date: 2026-09-03 09:12:02.057706
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import thursday_shared.db.base

revision: str = "9d8757dd4d47"
down_revision: str | None = "26294a50a735"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_runs",
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("task_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("agent_run_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("model_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("device_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("estimated_cost", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("model_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_model_runs_agent_run_id"), ["agent_run_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_model_runs_at"), ["at"], unique=False)
        batch_op.create_index(batch_op.f("ix_model_runs_device_id"), ["device_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_model_runs_model_id"), ["model_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_model_runs_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_model_runs_task_id"), ["task_id"], unique=False)

    op.create_table(
        "models",
        sa.Column("endpoint_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("device_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("model_name", sa.String(length=200), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("runtime", sa.String(length=32), nullable=False),
        sa.Column("model_type", sa.String(length=32), nullable=False),
        sa.Column("kind_override", sa.String(length=32), nullable=True),
        sa.Column("enabled_override", sa.Boolean(), nullable=True),
        sa.Column("context_length", sa.Integer(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("required_ram", sa.BigInteger(), nullable=False),
        sa.Column("required_vram", sa.BigInteger(), nullable=False),
        sa.Column("tokens_per_second", sa.Float(), nullable=False),
        sa.Column("online", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_benchmarked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("models", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_models_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_models_device_id"), ["device_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_models_endpoint_id"), ["endpoint_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_models_model_name"), ["model_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_models_model_type"), ["model_type"], unique=False)

    op.create_table(
        "model_endpoints",
        sa.Column("device_id", thursday_shared.db.base.GUID(length=36), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("runtime", sa.String(length=32), nullable=False),
        sa.Column("base_url", sa.String(length=512), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("capabilities", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("extra", thursday_shared.db.base.JSONColumn(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", thursday_shared.db.base.GUID(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("model_endpoints", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_model_endpoints_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_model_endpoints_device_id"), ["device_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_model_endpoints_last_seen_at"), ["last_seen_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_model_endpoints_provider"), ["provider"], unique=False)
        batch_op.create_index(batch_op.f("ix_model_endpoints_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model_endpoints", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_model_endpoints_status"))
        batch_op.drop_index(batch_op.f("ix_model_endpoints_provider"))
        batch_op.drop_index(batch_op.f("ix_model_endpoints_last_seen_at"))
        batch_op.drop_index(batch_op.f("ix_model_endpoints_device_id"))
        batch_op.drop_index(batch_op.f("ix_model_endpoints_created_at"))

    op.drop_table("model_endpoints")
    with op.batch_alter_table("models", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_models_model_type"))
        batch_op.drop_index(batch_op.f("ix_models_model_name"))
        batch_op.drop_index(batch_op.f("ix_models_endpoint_id"))
        batch_op.drop_index(batch_op.f("ix_models_device_id"))
        batch_op.drop_index(batch_op.f("ix_models_created_at"))

    op.drop_table("models")
    with op.batch_alter_table("model_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_model_runs_task_id"))
        batch_op.drop_index(batch_op.f("ix_model_runs_status"))
        batch_op.drop_index(batch_op.f("ix_model_runs_model_id"))
        batch_op.drop_index(batch_op.f("ix_model_runs_device_id"))
        batch_op.drop_index(batch_op.f("ix_model_runs_at"))
        batch_op.drop_index(batch_op.f("ix_model_runs_agent_run_id"))

    op.drop_table("model_runs")
    # ### end Alembic commands ###
