"""audit origin device

Revision ID: f7c584518f25
Revises: 4f8c9e549d09
Create Date: 2026-09-03 03:56:05.686223
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import thursday_shared.db.base

revision: str = "f7c584518f25"
down_revision: str | None = "4f8c9e549d09"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("origin_device_id", thursday_shared.db.base.GUID(length=36), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_column("origin_device_id")

    # ### end Alembic commands ###
